title: "Géraud COUDERT — Futur développeur Full-Stack SLAM"
email: "geraud.coudert@btsinfo-aurillac.fr"
description: >-
  Étudiant BTS SIO SLAM à Aurillac. Développeur Full-Stack : PHP, Java, C#, Android, MySQL.
  Disponible pour un stage de 6 semaines à partir de juin 2026.

# Navigation dans le header
header_pages:
  - competences.md
  - projets.md
  - contact.md

# Configuration des liens sociaux (affichés par le thème Minima)
github_username:  GeraudCoudert
linkedin_username: geraud-coudert

# URL GitHub Pages
url: "https://geraudcoudert.github.io"
baseurl: "/cv-en-ligne"

# Paramètres de build

plugins:
  - jekyll-feed
  - jekyll-seo-tag
